# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_RxSwift

  target 'MVVM_RxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxSwift', '~>5'
 	pod 'RxCocoa', '~> 5'
  end

  target 'MVVM_RxSwiftUITests' do
    # Pods for testing
  end

end
